import {test,expect,type Page} from '@playwright/test';
import {newForge,forgeAction,saveForge,type ForgeState} from '@three-card/core';
const act=(s:ForgeState,type:any,ids?:string[])=>{const r=forgeAction(s,{seq:s.seq,type,ids});if(r.error)throw Error(r.error);return r.state;};
function fixture(seed:string){let s=newForge(seed);s.phase='prepare';s.companions=['zhangfei','pursuit','chain','blade','huangzhong'].map(id=>({id:id as any,growth:0}));s=act(s,'begin');s.hand=['spear-7','cavalry-7','bow-2','scheme-4','spear-1','bow-9'];s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);s.target=5000;return s;}
async function load(page:Page,s:ForgeState){const saved:Record<string,string>={};saveForge({get:k=>saved[k]??null,set:(k,v)=>{saved[k]=v;}},s);await page.goto('http://127.0.0.1:4173');await page.evaluate(data=>{localStorage.clear();for(const[k,v]of Object.entries(data))localStorage.setItem(k,v);},saved);await page.reload();await click(page,'continue');}
async function click(page:Page,a:string){await page.locator(`[data-action="${a}"]`).click();if(!a.startsWith('card:'))await page.waitForTimeout(180);}
const read=(page:Page)=>page.evaluate(()=>JSON.parse((window as any).render_game_to_text()).view);
test('burst reveals actual events then banks the full score without a wager choice',async({page})=>{test.setTimeout(60000);await page.setViewportSize({width:1280,height:720});let s=fixture('0');for(let i=0;i<300;i++){s=fixture('ui-burst-'+i);if(act(s,'play',s.hand.slice(0,3)).result!.bursts>=2)break;if(i===299)throw Error('fixture not found');}await load(page,s);for(const id of s.hand.slice(0,3))await click(page,'card:'+id);await expect(page.locator('.burst-hint')).toContainText('35%');await click(page,'play');expect((await read(page)).score).toBe(0);await expect(page.locator('.total b')).toHaveText('···');await expect(page.locator('.causal-chain')).toBeVisible();await expect(page.locator('.causal-chain')).toContainText('额外计分');await expect(page.locator('.settlement-result')).toBeVisible();await expect(page.locator('.settlement-result')).toContainText('本手攻势已入账');await expect(page.locator('.ledger')).toContainText('响应额外计分');const settled=await read(page),gain=settled.result.total-settled.result.floor,formatted=new Intl.NumberFormat('zh-CN',{maximumFractionDigits:2}).format(gain);expect(settled.settlement).toBe('bank');expect(settled.score).toBe(settled.result.total);expect(gain).toBeGreaterThan(0);await expect(page.locator('.pursuit-gain')).toHaveText(`马超追击成功，本次连锁令最终攻势增加 ${formatted}`);expect(Number(await page.locator('.point-breakdown').getAttribute('data-points-sum'))).toBe(settled.result.chips);await expect(page.locator('.step-head em').first()).toContainText('→');await expect(page.locator('[data-action=gamble]')).toHaveCount(0);await expect(page.locator('[data-action=bank]')).toHaveCount(0);expect(await page.locator('[data-action=next]').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight)).toBe(true);expect(await page.locator('.causal-chain').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight)).toBe(true);await page.screenshot({path:'docs/evidence/burst-direct-settlement.png'});await page.reload();await click(page,'continue');expect(await read(page)).toEqual(settled);await expect(page.locator('.settlement-result')).toBeVisible();await expect(page.locator('.new-record')).toBeVisible();});

test('a hand without additional scoring uses ordinary settlement feedback',async({page})=>{let s=newForge('ordinary-settlement');s.phase='prepare';s.companions=[];s=act(s,'begin');s.hand=['spear-1','cavalry-2','bow-3','scheme-4','spear-5','bow-8'];s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);s.target=5000;await load(page,s);for(const id of s.hand.slice(0,3))await click(page,'card:'+id);await expect(page.locator('.score-panel .eyebrow')).toContainText('保底预览');await click(page,'play');await expect(page.locator('.battle-heading h2')).toHaveText('普通结算');await expect(page.locator('.score-panel .eyebrow')).toContainText('普通结算');if(await page.locator('[data-action=skip-animation]').count())await page.locator('[data-action=skip-animation]').click();await expect(page.locator('.chain-tier')).toHaveCount(0);await expect(page.locator('.pursuit-gain')).toHaveCount(0);});

test('skip and reduced motion reveal and bank without removing the ledger',async({page})=>{let s=fixture('causal-skip');await load(page,s);for(const id of s.hand.slice(0,3))await click(page,'card:'+id);await click(page,'play');await page.locator('[data-action=skip-animation]').click();await expect(page.locator('.causal-chain')).toBeVisible();await expect(page.locator('.ledger .score-step')).toHaveCount((await read(page)).result.steps.length);expect((await read(page)).settlement).toBe('bank');await page.emulateMedia({reducedMotion:'reduce'});s=fixture('causal-reduced');await load(page,s);for(const id of s.hand.slice(0,3))await click(page,'card:'+id);await click(page,'play');await expect(page.locator('.settlement-result')).toBeVisible();await expect(page.locator('[data-action=skip-animation]')).toHaveCount(0);expect((await read(page)).settlement).toBe('bank');await expect(page.locator('.ledger')).toBeVisible();});
test('victory extends into challenge with unchanged build and visible goal',async({page})=>{let s=fixture('endless-ui');s.stage=7;s.phase='victory';s.score=s.target=1900;s.stats.cleared=8;s.stats.best=2200;await load(page,s);await click(page,'extend');await expect(page.locator('.rarity-panel')).toBeVisible();await expect(page.locator('.shop-edit')).toBeVisible();await expect(page.locator('[data-action^="recruit:"]')).toHaveCount(0);await click(page,'depart');await expect(page.locator('h1')).toHaveText('极限挑战 · 第1层');await click(page,'begin:normal');const v=await read(page);expect(v.challenge).toBe(1);expect(v.target).toBe(3040);expect(v.army).toEqual(s.army);expect(v.companions).toEqual(s.companions);expect(v.stats.cleared).toBe(8);await page.screenshot({path:'docs/evidence/burst-endless.png'});});
