import {test,expect,type Page} from '@playwright/test';
import {newForge,forgeAction,saveForge,type ForgeState} from '@three-card/core';
const act=(s:ForgeState,type:any,ids?:string[])=>{const r=forgeAction(s,{seq:s.seq,type,ids});if(r.error)throw Error(r.error);return r.state;};
function fixture(seed:string){let s=newForge(seed);s.phase='prepare';s.companions=['zhangfei','pursuit','chain','blade','huangzhong'].map(id=>({id:id as any,growth:0}));s=act(s,'begin');s.hand=['spear-7','cavalry-7','bow-2','scheme-4','spear-1','bow-9'];s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);s.target=5000;return s;}
async function load(page:Page,s:ForgeState){const saved:Record<string,string>={};saveForge({get:k=>saved[k]??null,set:(k,v)=>{saved[k]=v;}},s);await page.goto('http://127.0.0.1:4173');await page.evaluate(data=>{localStorage.clear();for(const[k,v]of Object.entries(data))localStorage.setItem(k,v);},saved);await page.reload();await click(page,'continue');}
async function click(page:Page,a:string){await page.locator(`[data-action="${a}"]`).click();if(!a.startsWith('card:'))await page.waitForTimeout(180);}
const read=(page:Page)=>page.evaluate(()=>JSON.parse((window as any).render_game_to_text()).view);
test('burst reveals actual events then settles win and loss without rerolling',async({page})=>{test.setTimeout(60000);await page.setViewportSize({width:1280,height:720});for(const outcome of ['win','loss']){let s=fixture('0');for(let i=0;i<300;i++){s=fixture('ui-burst-'+i);const played=act(s,'play',s.hand.slice(0,3));if(played.result!.bursts>=2&&act(played,'gamble').settlement===outcome)break;if(i===299)throw Error('fixture not found');}await load(page,s);for(const id of s.hand.slice(0,3))await click(page,'card:'+id);await expect(page.locator('.burst-hint')).toContainText('35%');await click(page,'play');expect((await read(page)).score).toBe(0);await expect(page.locator('.total b')).toHaveText('···');await expect(page.locator('.wager-panel')).toBeVisible();await expect(page.locator('.ledger')).toContainText('连营发动');const revealed=await read(page);expect(Number(await page.locator('.point-breakdown').getAttribute('data-points-sum'))).toBe(revealed.result.chips);await expect(page.locator('.step-head em').first()).toContainText('→');expect(await page.locator('[data-action=gamble]').evaluate(e=>e.getBoundingClientRect().bottom<=innerHeight)).toBe(true);await page.screenshot({path:`docs/evidence/burst-${outcome}-pending.png`});const pending=await read(page);await page.reload();await click(page,'continue');expect(await read(page)).toEqual(pending);await click(page,'gamble');await expect(page.locator('.wager-result')).toHaveClass(new RegExp(outcome));const settled=await read(page);expect(settled.score).toBe(settled.result.total);await page.screenshot({path:`docs/evidence/burst-${outcome}-settled.png`});await page.reload();await click(page,'continue');expect(await read(page)).toEqual(settled);await expect(page.locator('[data-action=gamble]')).toHaveCount(0);await expect(page.locator('.new-record')).toBeVisible();}});
test('victory extends into challenge with unchanged build and visible goal',async({page})=>{let s=fixture('endless-ui');s.stage=7;s.phase='victory';s.score=s.target=1900;s.stats.cleared=8;s.stats.best=2200;await load(page,s);await click(page,'extend');await expect(page.locator('.rarity-panel')).toBeVisible();await click(page,'recruit:skip');await click(page,'edit-skip');await click(page,'depart');await expect(page.locator('h1')).toHaveText('极限挑战 · 第1层');await click(page,'begin:normal');const v=await read(page);expect(v.challenge).toBe(1);expect(v.target).toBe(3040);expect(v.army).toEqual(s.army);expect(v.companions).toEqual(s.companions);expect(v.stats.cleared).toBe(8);await page.screenshot({path:'docs/evidence/burst-endless.png'});});
