import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newRun,runAction,saveRun,loadRun,copy,newBattle,type RunState,type RunAction} from '@three-card/core';
function act(s:RunState,a:Omit<RunAction,'seq'>){const r=runAction(s,{...a,seq:s.seq});assert.equal(r.error,undefined);return r.state;}
function at(phase:RunState['phase']){const s=newRun('fixture');s.phase=phase;s.battle=null;s.layer=2;return s;}
const memory=()=>{const data=new Map<string,string>();return {data,get:(k:string)=>data.get(k)??null,set:(k:string,v:string)=>{data.set(k,v);}};};
test('camp applies exactly once and rejects stale commands',()=>{let s=at('camp');s.hp=12;const a={type:'camp' as const,seq:s.seq,choice:'heal',transactionId:'fixture:2:camp'};s=runAction(s,a).state;assert.equal(s.hp,22);assert.equal(s.layer,3);assert.equal(s.phase,'route');assert.equal(runAction(s,a).state,s);});
test('reward capacity replacement is atomic and candidates stable',()=>{const s=at('reward');s.tactics=['advance','fortify','supply'];s.reward={id:'r',kind:'tactic',candidates:['regroup','borrow-banner','star-reading']};const a={type:'claim' as const,seq:0,transactionId:'r',choice:'regroup'};assert.equal(runAction(s,a).state,s);const next=runAction(s,{...a,replace:'supply'});assert.equal(next.error,undefined);assert.deepEqual(next.state.tactics,['advance','fortify','regroup']);assert.equal(next.state.transactions.length,1);});
test('shop insufficient funds and repeat purchase cannot charge twice',()=>{let s=at('shop');s.gold=0;s.offers=[{id:'o',kind:'heal',item:'heal',price:12,sold:false}];s.hp=10;const a={type:'buy' as const,choice:'o',transactionId:'o'};assert.equal(runAction(s,{...a,seq:0}).state,s);s.gold=20;s=act(s,a);assert.equal(s.gold,8);assert.equal(s.hp,18);assert.equal(runAction(s,{...a,seq:s.seq}).state,s);});
test('banner event replacement cannot cost HP before valid selection',()=>{const s=at('event');s.event='abandoned-banner';s.tactics=['advance','fortify','supply'];const a={type:'event' as const,choice:'0',transactionId:'fixture:2:event'};assert.equal(runAction(s,{...a,seq:0}).state,s);const next=act(s,{...a,replace:'supply'});assert.equal(next.hp,35);assert.ok(next.tactics.includes('borrow-banner'));});
test('route selection only accepts listed layer nodes',()=>{let s=at('route');assert.equal(runAction(s,{seq:0,type:'enter',node:'boss'}).state,s);s=act(s,{type:'enter',node:'shop'});assert.equal(s.offers.length,4);assert.equal(new Set(s.offers.map(o=>o.id)).size,4);});
test('boss and elite use configured battle rules',()=>{let s=at('route');s.layer=7;s=act(s,{type:'enter',node:'boss'});assert.equal(s.battle?.enemyId,'zhang-jiao');assert.equal(s.battle?.enemyHp,40);});
test('battle end updates campaign statistics only once',()=>{let s=newRun('end');s.battle!.phase='battleEnd';s.battle!.victory=true;s.battle!.enemyHp=0;s.battle!.stats.rounds=4;s=act(s,{type:'finish-battle'});assert.equal(s.gold,32);assert.equal(s.stats.battles,1);assert.equal(s.phase,'reward');assert.equal(runAction(s,{seq:s.seq,type:'finish-battle'}).state,s);});
test('double-slot restore and star substate retain complete random state',()=>{const storage=memory();let s=newRun('save');s.battle=newBattle('star',{tactics:['star-reading']});s=act(s,{type:'battle',action:{seq:0,type:'tactic',tactic:'star-reading'}});saveRun(storage,s);assert.deepEqual(loadRun(storage).state,s);assert.equal(loadRun(storage).state?.battle?.phase,'star');const old=copy(s);s=act(s,{type:'battle',action:{seq:s.battle!.seq,type:'star-select',slot:2}});saveRun(storage,s);storage.set('three-card:v1:1','broken');assert.deepEqual(loadRun(storage).state,old);});
test('failed storage write leaves earlier slot usable',()=>{const storage=memory(),s=newRun('old');saveRun(storage,s);const bad={get:storage.get,set:()=>{throw Error('disk full');}};assert.throws(()=>saveRun(bad,newRun('new')));assert.deepEqual(loadRun(storage).state,s);});
test('incompatible snapshot is retained without loading',()=>{const storage=memory();const s=newRun('old');s.contentVersion='future';saveRun(storage,s);assert.equal(loadRun(storage).state,null);assert.ok(loadRun(storage).notice);assert.ok(storage.get('three-card:v1:0'));});
