import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newForge,forgeAction,previewForge,forgeView,rarityRates,saveForge,loadForge,isForgeState,bossEncounter,type ForgeState,type ForgeAction} from '@three-card/core';
import {COMPANION_IDS,companionRarity,forgeStage} from '@three-card/content';
const act=(s:ForgeState,a:Omit<ForgeAction,'seq'>)=>{const r=forgeAction(s,{...a,seq:s.seq});assert.equal(r.error,undefined);assert.ok(isForgeState(r.state));return r.state;};
function fixture(seed='burst'){let s=newForge(seed);s.phase='prepare';s.companions=['zhangfei','pursuit','chain','blade','huangzhong'].map(id=>({id:id as any,growth:0}));s=act(s,{type:'begin'});s.hand=['spear-7','cavalry-7','bow-2','scheme-4','spear-1','bow-9'];s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);return s;}
const storage=()=>{const m=new Map<string,string>();return{get:(k:string)=>m.get(k)??null,set:(k:string,v:string)=>{m.set(k,v);}};};
test('burst floor is RNG-free; real chain is bounded and reproducible',()=>{let hit=0,miss=0,max=0;for(let i=0;i<150;i++){const s=fixture('chain-'+i),before=structuredClone(s),ids=s.hand.slice(0,3),p=previewForge(s,ids);assert.deepEqual(s,before);const out=act(s,{type:'play',ids});assert.deepEqual(out,act(s,{type:'play',ids}));assert.equal(out.score,0);assert.equal(out.stats.best,0);assert.equal(out.result!.floor,p.total);assert.ok(out.result!.total>=p.total);assert.ok(out.result!.bursts<=3);assert.equal(out.rng.player,s.rng.player);assert.equal(out.rng.reward,s.rng.reward);assert.equal(out.rng.ai,s.rng.ai);if(out.result!.bursts)hit++;else miss++;max=Math.max(max,out.result!.bursts);}assert.ok(hit>0&&miss>0);assert.equal(max,3);});
test('pursuit needs a retrigger source and chain drum alone never fabricates bonuses',()=>{const s=fixture();s.companions=s.companions.filter(c=>c.id!=='zhangfei');const ids=s.hand.slice(0,3),out=act(s,{type:'play',ids});assert.equal(out.result!.bursts,0);assert.equal(out.result!.total,previewForge(s,ids).total);assert.equal(out.rng.enemy,s.rng.enemy);});
test('full hand score banks exactly once without consuming another random stream',()=>{let s=fixture('direct-settlement');s.score=50;s.stats.best=99999;s=act(s,{type:'play',ids:s.hand.slice(0,3)});const pending=s,total=s.result!.total,rng=structuredClone(s.rng),store=storage();saveForge(store,s);s=act(s,{type:'bank'});assert.equal(s.settlement,'bank');assert.equal(s.result!.total,total);assert.equal(s.score,50+total);assert.equal(s.stats.best,99999);assert.equal(s.stageBest,total);assert.deepEqual(s.rng,rng);assert.deepEqual(s,act(loadForge(store).state!,{type:'bank'}));const duplicate=forgeAction(s,{seq:s.seq,type:'bank'});assert.ok(duplicate.error);assert.equal(duplicate.state,s);assert.equal(forgeAction(s,{seq:pending.seq,type:'bank'}).state,s);});
test('next recovers a pending result while legacy wager results remain loadable',()=>{let pending=fixture('pending-result');pending.hands=1;pending=act(pending,{type:'play',ids:pending.hand.slice(0,3)});pending.target=pending.result!.total;const continued=act(pending,{type:'next'});assert.equal(continued.phase,'recruit');assert.equal(continued.score,pending.result!.total);for(const settlement of ['win','loss'] as const){const legacy=structuredClone(pending);legacy.settlement=settlement;legacy.score=legacy.result!.total;const store=storage();saveForge(store,legacy);const loaded=loadForge(store).state!;assert.equal(loaded.settlement,settlement);assert.equal(act(loaded,{type:'next'}).phase,'recruit');}});
test('quality thresholds use final stage peak and normalized live pool',()=>{assert.deepEqual(rarityRates(0,1000),{common:.75,rare:.22,legendary:.03});assert.deepEqual(rarityRates(500,1000),{common:.65,rare:.30,legendary:.05});assert.deepEqual(rarityRates(1000,1000),{common:.5,rare:.4,legendary:.1});const remaining=COMPANION_IDS.filter(id=>companionRarity(id)!=='legendary');const p=rarityRates(1000,1000,remaining);assert.equal(p.legendary,0);assert.ok(Math.abs(p.common+p.rare-1)<1e-12);});
test('weighted recruitment honors tiers, excludes owned and duplicates, persists offers',()=>{const counts={common:0,rare:0,legendary:0};for(let i=0;i<3000;i++){let s=fixture('rarity-'+i);s.companions=[];s.target=1;s=act(s,{type:'play',ids:s.hand.slice(0,3)});s=act(s,{type:'bank'});s.stageBest=0;s=act(s,{type:'next'});assert.equal(new Set(s.recruits).size,3);counts[companionRarity(s.recruits[0])]++;if(i===0){const st=storage();saveForge(st,s);assert.deepEqual(loadForge(st).state?.recruits,s.recruits);}}assert.ok(counts.common>2100&&counts.common<2400);assert.ok(counts.rare>560&&counts.rare<760);assert.ok(counts.legendary>45&&counts.legendary<135);});
test('endless retains build and deck, continues rewards, failure preserves base victory',()=>{let s=fixture('endless');s.stage=7;s.stats.cleared=7;s.target=1;s=act(s,{type:'play',ids:s.hand.slice(0,3)});s=act(s,{type:'next'});assert.equal(s.phase,'victory');const army=structuredClone(s.army),companions=structuredClone(s.companions),best=s.stats.best;s=act(s,{type:'extend'});assert.equal(s.phase,'recruit');assert.deepEqual(s.army,army);assert.deepEqual(s.companions,companions);s=act(s,{type:'recruit',id:'skip'});s=act(s,{type:'edit',id:'skip'});s=act(s,{type:'depart'});assert.equal(s.challenge,1);assert.equal(forgeStage(s).target,3040);assert.equal(bossEncounter(s),null);s=act(s,{type:'begin'});assert.equal(s.hands,4);assert.deepEqual(s.army,army);s.hands=1;s=act(s,{type:'play',ids:s.hand.slice(0,3)});s=act(s,{type:'next'});assert.equal(s.phase,'defeat');assert.equal(s.stats.cleared,8);assert.ok(s.stats.best>=best);assert.ok(!('rng' in forgeView(s)));});
