import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newForge,forgeAction,previewForge,forgeView,isForgeState,loadForge,saveForge,copy,type ForgeState,type ForgeAction,type ArmyCard} from '@three-card/core';
import {ALL_COMPANION_IDS,COMPANIONS,COMPANION_IDS,RARITY_NAMES,STAGES,type CompanionId} from '@three-card/content';
const act=(s:ForgeState,a:Omit<ForgeAction,'seq'>)=>{const r=forgeAction(s,{...a,seq:s.seq});assert.equal(r.error,undefined);assert.ok(isForgeState(r.state),`invalid after ${a.type} ${r.state.phase}`);return r.state;};
function fixture(ids:CompanionId[],cards:ArmyCard[]){let s=newForge('fixture');s.phase='prepare';s.companions=ids.map(id=>({id,growth:0}));s=act(s,{type:'begin'});for(const c of cards){const old=s.army.find(x=>x.id===c.id)!;Object.assign(old,c);}s.hand=cards.map(c=>c.id);s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);s.discard=[];return s;}
const c=(id:string,rank:number,suit:ArmyCard['suit']='spear',bonus=0):ArmyCard=>({id,rank,suit,bonus});
const pair=[c('spear-7',7),c('cavalry-7',7,'cavalry'),c('bow-2',2,'bow')];
const straight=[c('spear-1',1),c('cavalry-2',2,'cavalry'),c('bow-3',3,'bow')];
test('stable legacy effects still compose exactly',()=>{assert.equal(ALL_COMPANION_IDS.length,22);const s=fixture(['guanyu','zhangfei','huangzhong','blade'],pair),ids=s.hand;const before=copy(s);const p=previewForge(s,ids);assert.equal(p.chips,77);assert.equal(p.mult,9);assert.equal(p.total,693);assert.deepEqual(s,before);assert.deepEqual(previewForge(s,ids),p);const next=act(s,{type:'play',ids});assert.equal(next.companions[0].growth,1);assert.equal(next.result?.total,693);assert.equal(next.hands,3);assert.equal(forgeAction(next,{seq:s.seq,type:'play',ids}).state,next);});
test('12 active generals form three engines while all 22 stable ids remain loadable',()=>{const names=Object.values(COMPANIONS).map(c=>c.name);assert.equal(new Set(names).size,22);assert.equal(COMPANION_IDS.length,12);assert.deepEqual(COMPANION_IDS.map(id=>COMPANIONS[id].name),['关羽','张飞','马超','陆逊','刘备','诸葛亮','曹操','荀彧','周瑜','貂蝉','孙策','赵云']);assert.deepEqual(RARITY_NAMES,{common:'良将',rare:'名将',legendary:'传奇'});});
test('three complete engines prefer different hands from the same six cards',()=>{const hand=['spear-8','cavalry-8','scheme-1','scheme-4','scheme-7','bow-2'],best=(ids:CompanionId[])=>{const s=newForge('engine');s.phase='battle';s.companions=ids.map(id=>({id,growth:0}));s.hand=hand;s.draw=s.army.filter(c=>!hand.includes(c.id)).map(c=>c.id);let pick:string[]=[],score=-1;for(let i=0;i<4;i++)for(let j=i+1;j<5;j++)for(let k=j+1;k<6;k++){const chosen=[hand[i],hand[j],hand[k]],total=previewForge(s,chosen).total;if(total>score){score=total;pick=chosen;}}return pick;};assert.deepEqual(best(['guanyu','zhangfei','pursuit','chain']),['spear-8','cavalry-8','scheme-7']);assert.deepEqual(best(['liubei','zhugeliang','caocao','abacus']),['scheme-1','scheme-4','bow-2']);assert.deepEqual(best(['zhouyu','diaochan','oath','zhaoyun']),['scheme-1','scheme-4','scheme-7']);});
test('low-card effects repeat on last card, once per scoring event',()=>{const s=fixture(['liubei','zhugeliang'],straight);const p=previewForge(s,s.hand);assert.equal(p.chips,49);assert.equal(p.mult,7);assert.equal(p.total,343);});
test('straight growth and flexible sequence rules',()=>{const s=fixture(['zhaoyun','scroll'],[c('spear-1',1),c('cavalry-3',3,'cavalry'),c('bow-5',5,'bow')]);assert.equal(previewForge(s,s.hand).category,2);assert.equal(previewForge(s,s.hand).growth.zhaoyun,2);s.companions[0].growth=4;assert.equal(previewForge(s,s.hand).growth.zhaoyun,6);});
test('component display order cannot change additive and multiplicative result',()=>{const s=fixture(['zhouyu','oath'],[c('spear-1',1),c('spear-4',4),c('spear-8',8)]),reversed=copy(s);reversed.companions.reverse();assert.equal(previewForge(s,s.hand).total,previewForge(reversed,reversed.hand).total);});
test('remaining effects have observable independent contribution',()=>{
 for(const id of ['sunquan','lvbu','diaochan','simayi','drum','seal','granary','abacus'] as CompanionId[]){const cards=id==='lvbu'?[c('spear-7',7),c('cavalry-7',7,'cavalry'),c('bow-7',7,'bow')]:id==='diaochan'?[c('scheme-1',1,'scheme'),c('scheme-4',4,'scheme'),c('scheme-8',8,'scheme')]:pair;const s=fixture([id],cards);if(id==='simayi')s.hands=1;if(id==='seal')s.pressed=true;if(id==='abacus'){s.army=s.army.filter(c=>c.id!=='scheme-9');s.draw=s.draw.filter(id=>id!=='scheme-9');}const plain=copy(s);plain.companions=[];assert.ok(previewForge(s,s.hand).total>previewForge(plain,plain.hand).total,id);}
});
test('discard economy, extra discard and invalid command preserve state',()=>{let s=newForge('gold');s.phase='prepare';s.companions=[{id:'caocao',growth:0},{id:'horse',growth:0}];s=act(s,{type:'begin'});assert.equal(s.discards,3);const old=s;assert.equal(forgeAction(s,{seq:s.seq,type:'discard',ids:[s.hand[0],s.hand[0]]}).state,s);s=act(s,{type:'discard',ids:[s.hand[0]]});assert.equal(s.gold,old.gold+2);assert.equal(s.discards,2);assert.equal(s.hand.length,6);});
test('pressure, public boss rules and last-hand victory precedence',()=>{let s=newForge('boss');s.phase='prepare';s.stage=7;s=act(s,{type:'begin',pressed:true});assert.equal(s.target,Math.ceil(STAGES[7].target*1.5));assert.equal(s.hands,3);s.hands=1;s.target=1;s=act(s,{type:'play',ids:s.hand.slice(0,3)});s=act(s,{type:'next'});assert.equal(s.phase,'victory');assert.equal(s.stats.pressureWins,1);
 const p=fixture([],pair);p.stage=2;assert.equal(previewForge(p,p.hand).chips,2);p.stage=5;p.lastCategory=1;assert.equal(previewForge(p,p.hand).penalty,.5);
});
test('zero hands below target loses after showing result',()=>{let s=fixture([],straight);s.hands=1;s.target=9999;s=act(s,{type:'play',ids:s.hand});assert.equal(s.phase,'result');s=act(s,{type:'next'});assert.equal(s.phase,'defeat');});
test('every permanent edit survives next stage with unique physical IDs',()=>{
 for(const edit of ['copy','remove','rank','enhance','suit','level'] as const){let s=newForge('edit');s.phase='forge';s.pendingEdit=edit;const before=copy(s.army);s=act(s,{type:'edit',edit,cardId:'spear-1',suit:'bow',category:1});assert.equal(s.phase,'shop');if(edit==='copy'){assert.equal(s.army.length,37);assert.equal(new Set(s.army.map(c=>c.id)).size,37);}if(edit==='remove')assert.equal(s.army.length,35);if(edit==='rank')assert.equal(s.army[0].rank,3);if(edit==='enhance')assert.equal(s.army[0].bonus,12);if(edit==='suit')assert.equal(s.army[0].suit,'bow');if(edit==='level')assert.equal(s.levels[1],1);const after=copy(s.army);s=act(s,{type:'depart'});s=act(s,{type:'begin'});assert.deepEqual(s.army,after);if(edit!=='level')assert.notDeepEqual(s.army,before);}
});
test('invalid edit is atomic, copy preserves enhancement and capacity limits',()=>{let s=newForge('edit');s.phase='forge';s.army[0].bonus=24;s.pendingEdit='suit';const bad=forgeAction(s,{seq:0,type:'edit',edit:'suit',cardId:'spear-1',suit:'spear'});assert.equal(bad.state,s);s.pendingEdit='copy';s=act(s,{type:'edit',edit:'copy',cardId:'spear-1'});assert.equal(s.army.at(-1)?.bonus,24);s.phase='forge';s.pendingEdit='remove';s.army=s.army.slice(0,12);assert.equal(forgeAction(s,{seq:s.seq,type:'edit',edit:'remove',cardId:s.army[0].id}).state,s);});
test('recruit capacity, explicit replacement, sell growth and refresh costs',()=>{let s=newForge('market');s.phase='recruit';s.recruits=['guanyu'];s.companions=['liubei','zhouyu','sunquan','caocao','horse'].map(id=>({id:id as CompanionId,growth:0}));assert.equal(forgeAction(s,{seq:0,type:'recruit',id:'guanyu'}).state,s);s=act(s,{type:'recruit',id:'guanyu',replace:'horse'});s=act(s,{type:'edit',id:'skip'});s.gold=40;s.companions.find(c=>c.id==='guanyu')!.growth=8;s=act(s,{type:'sell',id:'guanyu'});assert.equal(s.gold,45);assert.equal(s.companions.length,4);s=act(s,{type:'refresh'});assert.equal(s.gold,42);assert.equal(s.refreshes,1);s=act(s,{type:'refresh'});assert.equal(s.gold,38);s.gold=0;assert.equal(forgeAction(s,{seq:s.seq,type:'buy',id:s.offers[0].id}).state,s);});
test('new save namespace restores rewards and stable former treasure ids without touching v1',()=>{const map=new Map<string,string>([['three-card:v1:0','old-save']]);const storage={get:(k:string)=>map.get(k)??null,set:(k:string,v:string)=>{map.set(k,v);}};let s=newForge('save');saveForge(storage,s);const old=copy(s);s=act(s,{type:'starter',id:'liubei'});s.companions=['pursuit','chain','blade','horse','granary'].map(id=>({id:id as CompanionId,growth:0}));saveForge(storage,s);assert.deepEqual(loadForge(storage).state,s);assert.deepEqual(loadForge(storage).state?.companions.map(c=>COMPANIONS[c.id].name),['马超','陆逊','太史慈','公孙瓒','鲁肃']);map.set('three-card:forge:v8:1','broken');assert.deepEqual(loadForge(storage).state,old);assert.ok(loadForge(storage).notice);assert.equal(map.get('three-card:v1:0'),'old-save');const broken=copy(s) as any;broken.army[1].id=broken.army[0].id;assert.equal(isForgeState(broken),false);broken.contentVersion='0.1.0';assert.equal(isForgeState(broken),false);});
test('replay reproduces draws, offers and scoring; view excludes future order',()=>{let a=newForge('repeat'),b=newForge('repeat');for(const cmd of [{type:'starter',id:'guanyu'},{type:'begin'}] as Omit<ForgeAction,'seq'>[]){a=act(a,cmd);b=act(b,cmd);}const ids=a.hand.slice(0,3);a=act(a,{type:'play',ids});b=act(b,{type:'play',ids});assert.deepEqual(a,b);assert.equal('rng' in forgeView(a),false);assert.equal('draw' in forgeView(a),false);});
