import {test} from 'node:test';
import assert from 'node:assert/strict';
import {newForge,forgeAction,previewForge,bossEncounter,forgeRule,saveForge,loadForge,copy,type ForgeState,type ForgeAction} from '@three-card/core';
const act=(s:ForgeState,a:Omit<ForgeAction,'seq'>)=>{const r=forgeAction(s,{...a,seq:s.seq});assert.equal(r.error,undefined);return r.state;};
function battle(stage:number){let s=newForge('boss-proof');s.phase='prepare';s.stage=stage;s=act(s,{type:'begin'});s.hand=['spear-1','cavalry-2','bow-3','scheme-4','spear-5','bow-8'];s.draw=s.army.filter(c=>!s.hand.includes(c.id)).map(c=>c.id);s.discard=[];return s;}
test('boss threshold changes only subsequent scoring and keeps resources / overflow',()=>{let s=battle(3);const threshold=bossEncounter(s)!.threshold;s.score=threshold-1;s.scouted=true;const ids=s.hand.slice(0,3),p=previewForge(s,ids),before=copy(s);s=act(s,{type:'play',ids});s=act(s,{type:'bank'});assert.equal(s.result?.total,p.total);assert.equal(s.score,before.score+p.total);assert.equal(bossEncounter(s)?.phase,1);assert.equal(forgeRule(s),'variety');s=act(s,{type:'next'});assert.equal(s.hands,before.hands-1);assert.equal(s.discards,before.discards);assert.equal(s.phase,'battle');s.lastCategory=previewForge(s,s.hand.slice(0,3)).category;assert.equal(previewForge(s,s.hand.slice(0,3)).penalty,.5);s.scouted=true;assert.equal(previewForge(s,s.hand.slice(0,3)).penalty,.5);});
test('thunder shelter requires playing a scheme card in the current hand',()=>{const s=battle(7);s.score=bossEncounter(s)!.threshold;const plain=previewForge(s,s.hand.slice(0,3)),scheme=previewForge(s,['spear-1','cavalry-2','scheme-4']);assert.equal(plain.penalty,.6);assert.ok(plain.steps.some(x=>x.text.includes('未上拍诡物')));assert.equal(scheme.penalty,1);assert.ok(scheme.steps.some(x=>x.source==='诡物压场'));assert.equal(act(s,{type:'play',ids:['spear-1','cavalry-2','scheme-4']}).result?.total,scheme.total);});
test('boss phase survives resume; invalid actions cannot change it',()=>{const s=battle(7);s.score=bossEncounter(s)!.threshold;const map=new Map<string,string>();const storage={get:(k:string)=>map.get(k)??null,set:(k:string,v:string)=>{map.set(k,v);}};saveForge(storage,s);const restored=loadForge(storage).state!;assert.deepEqual(restored,s);assert.equal(bossEncounter(restored)?.phase,1);const r=forgeAction(s,{seq:s.seq,type:'play',ids:[s.hand[0],s.hand[0],s.hand[1]]});assert.ok(r.error);assert.equal(r.state,s);});
test('lethal burst bypasses phases and last hand wins before exhaustion',()=>{for(const stage of [3,7]){let s=battle(stage);s.target=40;s.levels.fill(10);s.hands=1;const predicted=previewForge(s,s.hand.slice(0,3)).total;s=act(s,{type:'play',ids:s.hand.slice(0,3)});s=act(s,{type:'bank'});assert.equal(s.score,predicted);assert.ok(s.score>40);s=act(s,{type:'next'});assert.equal(s.phase,stage===7?'victory':'shop');assert.equal(s.stats.cleared,1);if(stage!==7){assert.equal(s.offers.length,3);assert.ok(s.pendingEdit);}}});
test('pressure shifts boss transition with total HP; ordinary stages have no boss',()=>{let s=battle(3);s.phase='prepare';s=act(s,{type:'begin',pressed:true});assert.equal(s.target,900);assert.equal(bossEncounter(s)?.threshold,360);s.score=359;assert.equal(bossEncounter(s)?.phase,0);s.score=360;assert.equal(bossEncounter(s)?.phase,1);assert.equal(bossEncounter(battle(2)),null);});
