import test from 'node:test';
import assert from 'node:assert/strict';
import {newTrigger,previewTrigger,actTrigger,isTriggerState,triggerView,type TriggerState} from '../packages/core/src/trigger';
import {TRIGGER_KINDS,type TriggerKind} from '../packages/content/src/trigger';
function fixture(kinds:TriggerKind[]){const s=newTrigger('fixture');s.deck=kinds.map((kind,i)=>({id:`c${i}`,kind,bonus:0}));s.hand=s.deck.map(c=>c.id);s.draw=[];return s;}
test('visible coin mirror hammer example is exactly 18 × 2 = 36; order changes result',()=>{const s=fixture(['coin','mirror','hammer']);const a=previewTrigger(s,['c0','c1','c2']);assert.equal(a.points,18);assert.equal(a.heat,2);assert.equal(a.total,36);assert.equal(a.extras,1);assert.equal(previewTrigger(s,['c2','c0','c1']).total,90);});
test('mirror repeats full candle ability and a mirror chain terminates to the left',()=>{const s=fixture(['candle','mirror','mirror']);const p=previewTrigger(s,s.hand);assert.equal(p.extras,3);assert.equal(p.points,15);assert.equal(p.heat,7);assert.equal(p.total,105);assert.equal(p.steps.length,6);});
test('all twelve cards trigger their stated effects including unmet conditions',()=>{const cases:[TriggerKind[],number][]=[ [['mirror','coin','vase'],3],[['coin','bell','vase'],1],[['mirror','bell','vase'],1],[['ledger','candle','mirror'],8],[['vase','mask','vase'],4],[['vase','prism','candle'],3],[['mirror','prism','candle'],7],[['vase','hourglass','hourglass'],1],[['coin','crown','vase'],6],[['mirror','crown','vase'],1] ];for(const [k,h] of cases){const s=fixture(k);assert.equal(previewTrigger(s,s.hand).heat,h,k.join(','));}assert.equal(TRIGGER_KINDS.length,12);});
test('preview is pure and stochastic scores never fall below guaranteed preview',()=>{let hits=0,misses=0;for(let n=0;n<100;n++){const s=newTrigger(`rng-${n}`);s.deck[0].kind='candle';s.deck[1].kind='glove';s.deck[2].kind='hammer';s.hand=['c0','c1','c2'];s.draw=s.deck.slice(3).map(c=>c.id);const before=structuredClone(s),p=previewTrigger(s,s.hand);assert.deepEqual(s,before);const a=actTrigger(s,{seq:0,type:'play',ids:s.hand}),b=actTrigger(structuredClone(s),{seq:0,type:'play',ids:s.hand});assert.deepEqual(a,b);assert.ok(a.result!.total>=p.total);a.result!.extras?hits++:misses++;}assert.ok(hits>25&&misses>25);});
test('invalid actions are atomic; stale sequence rejected and settlement banks once',()=>{const s=newTrigger('atomic'),before=structuredClone(s);assert.throws(()=>actTrigger(s,{seq:0,type:'play',ids:[s.hand[0],s.hand[0],s.hand[1]]}));assert.deepEqual(s,before);const a=actTrigger(s,{seq:0,type:'play',ids:s.hand.slice(0,3)});assert.equal(a.score,a.result!.total);assert.throws(()=>actTrigger(a,{seq:0,type:'next'}));const b=actTrigger(a,{seq:1,type:'next'});assert.equal(b.score,a.score);assert.throws(()=>actTrigger(b,{seq:2,type:'next'}));});
test('held cards survive refill and exhausted draw recycles unique physical cards',()=>{let s=newTrigger('refill');const held=s.hand.slice(3);s=actTrigger(s,{seq:s.seq,type:'play',ids:s.hand.slice(0,3)});s.score=0;s=actTrigger(s,{seq:s.seq,type:'next'});assert.ok(held.every(id=>s.hand.includes(id)));s=actTrigger(s,{seq:s.seq,type:'swap',ids:s.hand.slice(0,3)});assert.equal(s.hand.length,6);const all=[...s.hand,...s.draw,...s.discard];assert.equal(new Set(all).size,s.deck.length);});
test('last-hand win precedes defeat; reward and upgrades are single-use',()=>{let s=newTrigger('reward');s.hands=1;s.score=149;s=actTrigger(s,{seq:s.seq,type:'play',ids:s.hand.slice(0,3)});s=actTrigger(s,{seq:s.seq,type:'next'});assert.equal(s.phase,'reward');assert.equal(new Set(s.offers).size,3);const kind=s.offers[0];s=actTrigger(s,{seq:s.seq,type:'take',kind});assert.equal(s.deck.length,11);assert.throws(()=>actTrigger(s,{seq:s.seq,type:'take',kind}));const id=s.deck[0].id;s=actTrigger(s,{seq:s.seq,type:'upgrade',id});assert.equal(s.stage,1);assert.equal(s.deck[0].bonus,2);assert.equal(s.hands,4);assert.equal(s.hand.length,6);assert.throws(()=>actTrigger(s,{seq:s.seq,type:'upgrade',id}));});
test('third-stage success and exhausted failure terminate',()=>{for(const won of [false,true]){let s=newTrigger('end');s.stage=2;s.hands=1;s.score=won?419:0;s=actTrigger(s,{seq:0,type:'play',ids:s.hand.slice(0,3)});s=actTrigger(s,{seq:1,type:'next'});assert.equal(s.phase,won?'victory':'defeat');}});
test('new saves roundtrip, obsolete saves rejected, public view hides random streams and deck order',()=>{const s=newTrigger('save');assert.ok(isTriggerState(JSON.parse(JSON.stringify(s))));assert.ok(!isTriggerState({schemaVersion:8}));assert.ok(!isTriggerState({...s,hand:['fake']}));assert.ok(!isTriggerState({...s,deck:[...s.deck,s.deck[0]]}));const v=triggerView(s);assert.ok(!('draw' in v));assert.ok(!('rng' in v));assert.ok(!('burst' in v));});
