import {newRun,runAction,runView,saveRun,loadRun,backupRun,evaluate,type RunState,type RunAction,type BattleAction,type Card} from '@three-card/core';
import {TACTICS,RELICS,ENEMIES,EVENTS,NODE_NAMES,SUIT_NAMES,SUITS,HAND_NAMES,type TacticId,type RelicId,type Suit,type NodeKind} from '@three-card/content';
const root=document.querySelector<HTMLDivElement>('#app')!;
const storage={get:(k:string)=>localStorage.getItem(k),set:(k:string,v:string)=>localStorage.setItem(k,v)};
let run:RunState|null=null,notice='',home=true,selected=0,enemySlot=1,paused=false,modal='',muted=true,lastInput=-Infinity;
let pending:Omit<RunAction,'seq'>|null=null;
type Profile={finished:string[];wins:number;runs:number;bestDamage:number;relics:RelicId[];tutorialComplete:boolean};
let profile:Profile={finished:[],wins:0,runs:0,bestDamage:0,relics:[],tutorialComplete:false};
try{const p=JSON.parse(localStorage.getItem('three-card:profile:v1')??'null');if(p&&Array.isArray(p.finished)&&Array.isArray(p.relics)&&typeof p.wins==='number'&&typeof p.runs==='number')profile=p;}catch{}
function saveProfile(){if(!run)return;profile.tutorialComplete ||= run.tutorialComplete;profile.relics=[...new Set([...profile.relics,...run.relics])];if(['victory','defeat'].includes(run.phase)&&!profile.finished.includes(run.seed)){profile.finished.push(run.seed);profile.runs++;if(run.phase==='victory')profile.wins++;profile.bestDamage=Math.max(profile.bestDamage,run.stats.maxDamage);}try{localStorage.setItem('three-card:profile:v1',JSON.stringify(profile));}catch{notice='战绩未能保存。';}}

try{const loaded=loadRun(storage);run=loaded.state;notice=loaded.notice??'';}catch{notice='无法读取本地存档。请检查磁盘和浏览器存储设置。';}
const esc=(v:unknown)=>String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const button=(label:string,action:string,disabled=false,cls='')=>`<button class="${cls}" data-action="${esc(action)}" ${disabled?'disabled':''}>${label}</button>`;
const item=(id:string)=>Object.hasOwn(TACTICS,id)?TACTICS[id as TacticId]:RELICS[id as RelicId];
function persist(){if(run)try{saveRun(storage,run);}catch{notice='存档写入失败；当前可继续游玩，关闭前请检查存储空间。';}}
function start(mode:'campaign'|'single',tutorial=false){try{backupRun(storage);}catch{}const seed=(document.querySelector<HTMLInputElement>('#seed')?.value.trim()||crypto.randomUUID()).slice(0,100);run=newRun(seed,{mode,tutorial});selected=0;home=false;modal='';paused=false;notice='';persist();render();}
function dispatch(a:Omit<RunAction,'seq'>){if(!run)return;const result=runAction(run,{...a,seq:run.seq});if(result.error){notice=result.error;}else{run=result.state;notice='';modal='';pending=null;persist();saveProfile();sound();}render();}
function battle(a:Omit<BattleAction,'seq'>){if(run?.battle)dispatch({type:'battle',action:{...a,seq:run.battle.seq}});}
let audio:AudioContext|undefined;
function sound(){if(muted||paused)return;try{audio??=new AudioContext();void audio.resume();const o=audio.createOscillator(),g=audio.createGain();o.connect(g);g.connect(audio.destination);o.frequency.value=run?.battle?.result?160:420;g.gain.setValueAtTime(.035,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+.12);o.start();o.stop(audio.currentTime+.13);}catch{}}
function card(c:Card|null,i:number,side='own'){const active=side==='own'?selected===i:enemySlot===i;return `<button class="card ${c?c.suit:'hidden'} ${active?'selected':''}" data-action="${side}:${i}" aria-label="${side==='own'?'己方':'敌方'}第${i+1}张 ${c?SUIT_NAMES[c.suit]+c.rank:'暗牌'}" aria-pressed="${active}">${c?`<span class="rank">${c.rank}<small>${SUIT_NAMES[c.suit]}</small></span><span class="sigil">${SUIT_NAMES[c.suit]}</span><span class="card-foot">${side==='own'?`${i+1} · `:''}${SUIT_NAMES[c.suit]}阵</span>`:'<span class="seal">隐</span><span class="card-foot">情报未明</span>'}</button>`;}
function hp(n:number,max:number){return `<meter min="0" max="${max}" value="${n}"></meter><strong>${n}<small> / ${max} 兵力</small></strong>`;}
function header(){return `<header><a data-action="home" href="#">三国 <span>· 三张定天下</span></a><div>第一章 · 黄巾初起 <span class="tag">开发中 Demo</span></div><nav><a href="./index.html">构筑版 ↗</a>${button(muted?'音效：关':'音效：开','mute')}${button('牌型 / 规则','help')}</nav></header>`;}
function render(){const v=run?runView(run):null;let body='';
if(home){body=`<section class="home"><div><p class="eyebrow">THREE CARDS. ONE KINGDOM.</p><h1>三张布阵<br><em>一念进退</em></h1><p class="intro">以赵云之名，穿越黄巾战火。<br>换阵、探敌、施计——用三张牌打出自己的天下。</p><label class="seed-label">征程种子（留空随机）<input id="seed" maxlength="100" placeholder="例如：balance-0" autocomplete="off"></label><div class="start">${run?button('继续征程','continue',false,'primary'):''}${button('开始征程','new',false,'primary')}${button('新兵演练','tutorial')}${button('单战试炼','single')}${button('战绩 / 图鉴','profile')}</div><p class="muted">离线单人 · 八层征程 · 自动存档<br>鼠标操作 / 1–3 选牌 / Enter 亮阵与下一轮</p></div><div class="hero-art"><span class="moon"></span><img src="./assets/zhao-yun.png" alt="赵云"><div class="hero-caption">常山赵子龙 <small>每轮首次换阵免费</small></div></div></section>`;}
else if(v){const b=v.battle;body=`<div class="workspace"><aside class="left"><p class="eyebrow">常山 · 龙胆</p><h2>赵云</h2>${hp(v.hp,v.maxHp)}<p class="gold">军资 <b>${v.gold}</b></p><h3>行军路线 <small>${Math.min(v.layer+1,8)} / 8</small></h3><div class="route-track">${Array.from({length:8},(_,i)=>`<span class="${i<v.layer?'done':i===v.layer?'current':''}">${i+1}</span>`).join('')}</div><p class="muted">${v.path.map(n=>NODE_NAMES[n]).join(' → ')}</p><h3>军宝 <small>${v.relics.length} / 4</small></h3>${v.relics.length?v.relics.map(id=>`<div class="inventory"><b>${RELICS[id].name}</b><p>${RELICS[id].text}</p></div>`).join(''):'<p class="muted">征途中获取军宝，改变你的打法。</p>'}<div class="trait"><b>龙胆</b><p>每轮首次换阵免费。<br>兵力带入下一场战斗。</p></div></aside><main>`;
if(v.phase==='battle'&&b){const arranging=b.phase==='arrange',tutorial=b.tutorial&&b.round<=2;body+=`<div class="battle-top"><div><p class="eyebrow">${tutorial?'新兵演练':'两军对垒'} · 第 ${b.round} 轮</p>${tutorial?button('跳过演练','skip-tutorial'):''}<h2>${ENEMIES[b.enemyId].name}<span class="tag">${ENEMIES[b.enemyId].temperament}</span></h2></div><div class="enemy-hp">${hp(b.enemyHp,ENEMIES[b.enemyId].hp)}</div></div><div class="enemy-line"><img class="enemy-art" src="./assets/yellow-turban.png" alt="黄巾军"><div class="cards enemy-cards">${b.enemy.map((c,i)=>card(c,i,'enemy')).join('')}</div></div><div class="battle-divider"><span>战势 <b>${b.pressure}</b></span><span>${b.result?esc(b.result.detail):tutorial?(b.round===1?'演练①：2、3、4 组成连阵，点击「亮阵」。':'演练②：选择中间的骑3，免费换阵后亮阵。'):'敌方暗牌可侦察；加压可能逼退敌人，也会提高败阵伤害。'}</span></div><div class="own-line"><div class="cards">${b.player.map((c,i)=>card(c,i)).join('')}</div><div class="hand-info"><p>当前阵型</p><h3>${HAND_NAMES[evaluate(b.player).category]}</h3><p>军令 <b>${b.command}</b> / 4<br>护甲 <b>${b.shield}</b></p></div></div><div class="arrange">${button(`换阵 · ${b.exchanges===0?'免费':'1 军令'}`, 'exchange',!arranging||b.exchanges>=b.exchangeLimit)}${button('侦察 · 1 军令','scout',!arranging||b.command<1||b.scouts>=b.scoutLimit||b.enemy[enemySlot]!==null)}<span>换阵 ${b.exchanges}/${b.exchangeLimit} · 侦察 ${b.scouts}/${b.scoutLimit}</span></div><div class="decisions">${arranging?button('亮阵  ↵','show',false,'primary')+button('加压决战','press',tutorial,'danger')+button('撤阵 · 损失3兵力','withdraw',tutorial):b.phase==='roundEnd'?button('下一轮  ↵','next',false,'primary'):b.phase==='battleEnd'?button(b.victory?'战斗胜利 · 收取战果':'战斗结束 · 查看战报','finish',false,'primary'):''}</div>`;
}else if(v.phase==='route'){body+=`<section class="node"><p class="eyebrow">第 ${v.layer+1} 层 · 选择前路</p><h1>兵贵神速</h1><p>选择下一站。已走过的路，无法回头。</p><div class="choices">${v.routes.map(n=>button(NODE_NAMES[n],`route:${n}`,false,'choice')).join('')}</div></section>`;}
else if(v.phase==='reward'&&v.reward){body+=`<section class="node"><p class="eyebrow">战利品 · 军资已入账</p><h1>收兵，整军</h1><p>选择一件战利品，加入本局构筑。</p><div class="choices">${v.reward.candidates.map(id=>button(`<b>${item(id).name}</b><p>${item(id).text}</p>`,`claim:${id}`,false,'choice')).join('')}</div>${button(`跳过 · +${v.reward.kind==='tactic'?6:10} 军资`,'claim:skip')}</section>`;}
else if(v.phase==='camp'){body+=`<section class="node"><p class="eyebrow">篝火未熄</p><h1>扎营休整</h1><p>今夜的选择，会改变明日的战局。</p><div class="choices">${button('休养 · 恢复10兵力','camp:heal',false,'choice')}${button('操练 · 兵力上限与当前值+4','camp:train',false,'choice')}</div></section>`;}
else if(v.phase==='event'&&v.event){const e=EVENTS[v.event];body+=`<section class="node"><p class="eyebrow">途中奇遇</p><h1>${e.name}</h1><p>${e.story}</p><div class="choices">${e.options.map((o,i)=>button(o,`event:${i}`,false,'choice')).join('')}</div></section>`;}
else if(v.phase==='shop'){body+=`<section class="node"><p class="eyebrow">行军商队</p><h1>备战之物</h1><div class="choices">${v.offers.map(o=>button(`<b>${o.kind==='heal'?'军医 · 恢复8兵力':item(o.item).name}</b><p>${o.kind==='heal'?'每次到访仅可治疗一次':item(o.item).text}</p><strong>${o.sold?'已售罄':o.price+' 军资'}</strong>`,`buy:${o.id}`,o.sold||v.gold<o.price,'choice')).join('')}</div>${button('继续行军','leave',false,'primary')}</section>`;}
else{body+=`<section class="node"><p class="eyebrow">征程战报</p><h1>${v.phase==='victory'?'此战，天下闻名':'胜败乃兵家常事'}</h1><p>${v.mode==='single'?'单战试炼结束':v.phase==='victory'?'黄巾已破。第一章通关。':'整顿旗鼓，下一次再战。'}</p><div class="stats"><div><b>${v.stats.battles}</b>场战斗</div><div><b>${v.stats.rounds}</b>轮交锋</div><div><b>${v.stats.maxDamage}</b>最高伤害</div><div><b>${v.stats.pressureWins} / ${v.stats.pressureLosses}</b>加压胜 / 负</div></div>${button('再启征程','new',false,'primary')}${button('返回主界面','home')}</section>`;}
body+=`</main><aside class="right"><h3>随行锦囊 <small>${v.tactics.length} / 3</small></h3><p class="muted">每场每张一次，每轮限一张。消耗1军令。</p>${v.tactics.map(id=>button(`<b>${TACTICS[id].name}</b><p>${TACTICS[id].text}</p>${b?.used.includes(id)?'<small>本场已用</small>':''}`,`tactic:${id}`,v.phase!=='battle'||b?.phase!=='arrange'||b.command<1||b.tacticUsed||b.used.includes(id),'tactic')).join('')}<h3>战场纪事</h3><div class="log">${b?b.log.slice(-7).reverse().map(l=>`<p>${esc(l)}</p>`).join(''):'<p>山河破碎，英雄起于微末。</p>'}</div></aside></div>`;
}
let overlay='';
if(v?.battle?.phase==='star'&&!home){overlay=`<h2>观星 · 选择下一张援军</h2><p>军令已消耗，选定后返回布阵。</p><div class="cards">${v.battle.star.map((c,i)=>card(c,i,'star')).join('')}</div>`;}
else if(paused&&!home){overlay=`<h2>行军暂歇</h2><p>游戏失去焦点，已暂停音效与操作。进度已保存。</p>${button('继续','resume',false,'primary')}`;}
else if(modal==='profile'){overlay=`<h2>军中战绩</h2><p>完成 ${profile.runs} 局 · 胜利 ${profile.wins} 局 · 最高伤害 ${profile.bestDamage}</p><h3>军宝图鉴</h3>${Object.entries(RELICS).map(([id,r])=>`<p><b>${profile.relics.includes(id as RelicId)?r.name:'未发现'}</b> · ${profile.relics.includes(id as RelicId)?r.text:'征途中获得后记录'}</p>`).join('')}<p>战绩与图鉴仅作记录，不增加战斗数值。</p>${button('返回','close')}`;}
else if(modal==='help'){overlay=`<h2>三张定胜负</h2><p>牌型从强到弱：</p><ol>${[...HAND_NAMES].reverse().map(n=>`<li>${n}</li>`).join('')}</ol><p>同型比较点数。9、1、2 不连阵，兵种不分高低。</p><p>亮阵伤害 = 4 + 2×战势 + 牌型加值。加压立即决断，败阵伤害也随之提高；敌军退让只损失 2+战势 兵力。撤阵固定损失3。第8轮起双方存活则额外损失4。</p><p>选择己方牌后换阵或用锦囊；选择敌方暗牌后侦察。1–3选牌，Enter亮阵/下一轮，Esc关闭弹窗。</p>${button('明白了','close',false,'primary')}`;}
else if(modal==='press'){overlay=`<h2>加压决战</h2><p>敌军可退让或接战。接战立即亮阵，双方伤害都提高。</p>${button('战势2 · 立即决断','pressure:2',!!v?.battle&&v.battle.pressure>=2,'danger')}${button('战势3 · 立即决断','pressure:3',false,'danger')}${button('再想想','close')}`;}
else if(modal==='suit'){overlay=`<h2>借旗 · 选择新兵种</h2>${SUITS.map(s=>button(SUIT_NAMES[s],`suit:${s}`,v?.battle?.player[selected].suit===s)).join('')}${button('取消','close')}`;}
else if(modal==='regroup'){overlay=`<h2>重整 · 选择换掉的两张牌</h2>${[[0,1],[0,2],[1,2]].map(s=>button(`第${s[0]+1}与第${s[1]+1}张`,`regroup:${s.join(',')}`)).join('')}${button('取消','close')}`;}
else if(modal==='replace'&&pending&&v){const owned=pending.type==='claim'&&v.reward?.kind==='relic'||pending.type==='buy'&&v.offers.find(o=>o.id===pending!.choice)?.kind==='relic'?v.relics:v.tactics;overlay=`<h2>行囊已满 · 选择替换</h2><p>确认后领取新物品，并移除所选物品。</p>${owned.map(id=>button(item(id).name,`replace:${id}`)).join('')}${button('取消','close')}`;}
else if(modal.startsWith('new:')){overlay=`<h2>开启新征程？</h2><p>当前征程将被新的进度替代。</p>${button('确认启程',modal.replace('new:','start:'),false,'primary')}${button('继续原征程','close')}`;}
root.innerHTML=header()+body+(notice?`<div class="notice" role="status">${esc(notice)}${button('关闭提示','dismiss')}</div>`:'')+(overlay?`<div class="overlay"><section class="dialog" role="dialog" aria-modal="true">${overlay}</section></div>`:'');
}
function transact(a:Omit<RunAction,'seq'>,kind?:'tactic'|'relic'){if(!run)return;const owned=kind==='relic'?run.relics:run.tactics;if(kind&&owned.length>=(kind==='relic'?4:3)){pending=a;modal='replace';render();}else dispatch(a);}
function handle(action:string){const [id,...rest]=action.split(':');const value=rest.join(':');if(id==='dismiss'){notice='';render();return;}if(id==='mute'){muted=!muted;if(muted)void audio?.suspend();render();return;}if(id==='resume'){paused=false;render();return;}if(paused&&!home)return;
if(id==='home'){home=true;modal='';render();return;}if(id==='continue'){home=false;render();return;}if(id==='help'||id==='profile'){modal=id;render();return;}if(id==='close'){modal='';pending=null;render();return;}
if(['new','single','tutorial'].includes(id)){if(run&&run.phase!=='victory'&&run.phase!=='defeat'){modal=`new:${id}`;render();}else start(id==='single'?'single':'campaign',id==='tutorial');return;}if(id==='start'){start(value==='single'?'single':'campaign',value==='tutorial');return;}
if(!run||home)return;if(id==='skip-tutorial'){start('campaign');return;}if(id==='own'){selected=Number(value);render();return;}if(id==='enemy'){enemySlot=Number(value);render();return;}if(id==='star'){battle({type:'star-select',slot:Number(value)});return;}
if(id==='exchange')battle({type:'exchange',slot:selected});else if(id==='scout')battle({type:'scout',slot:enemySlot});else if(id==='show'||id==='withdraw')battle({type:'commit',mode:id==='show'?'show':'withdraw'});else if(id==='next')battle({type:'next'});else if(id==='finish')dispatch({type:'finish-battle'});else if(id==='press'){modal='press';render();}else if(id==='pressure')battle({type:'commit',mode:'press',pressure:Number(value)});
else if(id==='tactic'){if(value==='borrow-banner'){modal='suit';render();}else if(value==='regroup'){modal='regroup';render();}else battle({type:'tactic',tactic:value as TacticId,slot:selected});}
else if(id==='suit')battle({type:'tactic',tactic:'borrow-banner',slot:selected,suit:value as Suit});else if(id==='regroup')battle({type:'tactic',tactic:'regroup',slots:value.split(',').map(Number)});
else if(id==='route')dispatch({type:'enter',node:value as NodeKind});else if(id==='claim')transact({type:'claim',choice:value,transactionId:run.reward!.id},value==='skip'?undefined:run.reward!.kind);else if(id==='camp')dispatch({type:'camp',choice:value,transactionId:runView(run).transactionId});else if(id==='event')transact({type:'event',choice:value,transactionId:runView(run).transactionId},value==='0'&&run.event==='abandoned-banner'&&!run.tactics.includes('borrow-banner')?'tactic':undefined);else if(id==='buy'){const o=run.offers.find(o=>o.id===value)!;transact({type:'buy',choice:value,transactionId:value},o.kind==='heal'?undefined:o.kind);}else if(id==='replace'&&pending)dispatch({...pending,replace:value});else if(id==='leave')dispatch({type:'leave'});
}
root.addEventListener('click',e=>{const target=(e.target as HTMLElement).closest<HTMLElement>('[data-action]');if(!target)return;e.preventDefault();if(target instanceof HTMLButtonElement&&target.disabled)return;const now=performance.now();if(now-lastInput<180)return;lastInput=now;handle(target.dataset.action!);});
window.addEventListener('keydown',e=>{if(e.repeat||e.altKey||e.ctrlKey||e.metaKey||e.target instanceof HTMLInputElement)return;if(e.key==='Escape'){if(modal){handle('close');e.preventDefault();}return;}if(home||paused||modal||run?.battle?.phase==='star')return;if(['1','2','3'].includes(e.key)){selected=Number(e.key)-1;render();e.preventDefault();}if(e.key==='Enter'){e.preventDefault();handle(run?.battle?.phase==='arrange'?'show':run?.battle?.phase==='roundEnd'?'next':run?.battle?.phase==='battleEnd'?'finish':'');}});
function pause(){if(!home){paused=true;persist();void audio?.suspend();render();}}
window.addEventListener('blur',pause);
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});
(window as Window & {desktopLifecycle?:{onPause:(callback:()=>void)=>void}}).desktopLifecycle?.onPause(pause);
Object.assign(window,{render_game_to_text:()=>JSON.stringify({home,paused,view:run?runView(run):null})});
render();
