import {_electron as electron} from '@playwright/test';
import {mkdtemp,writeFile} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import path from 'node:path';
import assert from 'node:assert/strict';
const userData=await mkdtemp(path.join(tmpdir(),'three-card-smoke-'));
const executablePath=process.env.THREE_CARD_EXECUTABLE;
const launch=()=>electron.launch({...executablePath?{executablePath,args:[]}:{args:['apps/desktop/main.cjs']},env:{...process.env,THREE_CARD_USER_DATA:userData}});
let app=await launch();let page=await app.firstWindow();await page.waitForSelector('.legacy-link');await page.locator('.legacy-link').click();await page.waitForSelector('[data-action="tutorial"]');
const errors=[];page.on('pageerror',e=>errors.push(e.message));
const click=async action=>{await page.locator(`[data-action="${action}"]`).click();await page.waitForTimeout(200);};
await page.locator('#seed').fill('balance-10');await click('new');await click('show');
const before=await page.evaluate(()=>JSON.parse(window.render_game_to_text()).view);
assert.equal(before.battle.phase,'roundEnd');
assert.equal(await page.evaluate(()=>getComputedStyle(document.body).backgroundColor),'rgb(17, 30, 32)');
assert.equal(await page.evaluate(()=>typeof window.require),'undefined');
await page.screenshot({path:'docs/evidence/desktop-battle.png'});
await app.evaluate(({app,BrowserWindow})=>{app.focus({steal:true});BrowserWindow.getAllWindows()[0].focus();});
await page.waitForTimeout(300);
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].minimize());
await page.waitForSelector('[data-action="resume"]');
assert.equal(await page.evaluate(()=>JSON.parse(window.render_game_to_text()).paused),true);
await app.evaluate(({BrowserWindow})=>BrowserWindow.getAllWindows()[0].restore());
await page.screenshot({path:'docs/evidence/desktop-paused.png'});
await app.close();app=await launch();page=await app.firstWindow();await page.waitForSelector('.legacy-link');await page.locator('.legacy-link').click();await page.waitForSelector('[data-action="continue"]');await page.locator('[data-action="continue"]').click();
assert.deepEqual(await page.evaluate(()=>JSON.parse(window.render_game_to_text()).view),before);
await page.screenshot({path:'docs/evidence/desktop-restored.png'});
for(let step=0;step<250;step++){
 const v=await page.evaluate(()=>JSON.parse(window.render_game_to_text()).view);if(['victory','defeat'].includes(v.phase))break;
 if(v.phase==='battle')await click(v.battle.phase==='battleEnd'?'finish':v.battle.phase==='roundEnd'?'next':'show');
 else if(v.phase==='reward')await click('claim:skip');
 else if(v.phase==='route')await click('route:'+(v.routes.includes('camp')?'camp':v.routes.includes('event')?'event':v.routes.includes('battle')?'battle':v.routes[0]));
 else if(v.phase==='camp')await click('camp:heal');
 else if(v.phase==='event')await click(v.event==='physician'?'event:0':'event:1');else await click('leave');
}
assert.equal(await page.evaluate(()=>JSON.parse(window.render_game_to_text()).view.phase),'victory');
await page.screenshot({path:'docs/evidence/desktop-campaign-victory.png'});
await app.close();assert.deepEqual(errors,[]);
await writeFile('docs/evidence/desktop-smoke.json',JSON.stringify({platform:process.platform,arch:process.arch,packaged:!!executablePath,offline:true,rendererNodeDisabled:true,minimizePause:true,restartRestore:true,fullCampaignVictory:true,userData,errors},null,2)+'\n');
console.log('Desktop offline load, sandbox, minimize pause and restart restore passed.');
